name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build for Windows
      run: |
        cd server
        GOOS=windows GOARCH=amd64 go build -o marku-server-${{ github.event.inputs.version }}-windows-amd64.exe main.go
        
    - name: Build for Linux
      run: |
        cd server
        GOOS=linux GOARCH=amd64 go build -o marku-server-${{ github.event.inputs.version }}-linux-amd64 main.go
        
    - name: Prepare Windows Package
      run: |
        mkdir -p dist/windows
        mkdir -p dist/windows/data
        cp server/marku-server-${{ github.event.inputs.version }}-windows-amd64.exe dist/windows/
        cp server/config.ini.example dist/windows/config.ini
        cd dist/windows
        zip -r ../../marku-server-${{ github.event.inputs.version }}-windows-amd64.zip .
        
    - name: Prepare Linux Package
      run: |
        mkdir -p dist/linux
        mkdir -p dist/linux/data
        cp server/marku-server-${{ github.event.inputs.version }}-linux-amd64 dist/linux/
        cp server/config.ini.example dist/linux/config.ini
        cd dist/linux
        tar -czf ../../marku-server-${{ github.event.inputs.version }}-linux-amd64.tar.gz .
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        body: |
          ## Changes
          
          - Automated release for version ${{ github.event.inputs.version }}
          - Cross-platform builds for Windows and Linux
          
          ## Downloads
          
          - **Windows**: marku-server-${{ github.event.inputs.version }}-windows-amd64.zip
          - **Linux**: marku-server-${{ github.event.inputs.version }}-linux-amd64.tar.gz
          
          ## Package Contents
          
          每个压缩包都包含：
          - 可执行文件（marku-server）
          - 配置文件（config.ini）
          - 数据目录（data/）
        draft: false
        prerelease: false
        files: |
          ./marku-server-${{ github.event.inputs.version }}-windows-amd64.zip
          ./marku-server-${{ github.event.inputs.version }}-linux-amd64.tar.gz